# PRECISION DEFAULT: SINGLE                     
set(FVCOM_PRECISION "SINGLE" CACHE STRING "FVCOM PRECISION")
set_property(CACHE FVCOM_PRECISION PROPERTY STRINGS "SINGLE;DOUBLE")

# SELECT SPHERICAL COORDINATES FOR INTEGRATION
set(FVCOM_SPHERICAL OFF CACHE BOOL "SELECT SPHERICAL COORDINATES FOR INTEGRATION")

# INCLUDE WET/DRY TREATMENT OF DOMAIN
set(FVCOM_WET_DRY ON CACHE BOOL "INCLUDE WET/DRY TREATMENT OF DOMAIN")

# ENABLE PARALLELIZATION WITH MPI
set(FVCOM_MULTIPROCESSOR ON CACHE BOOL "ENABLE PARALLELIZATION WITH MPI")

if(FVCOM_MULTIPROCESSOR EQUAL ON)
  # INCLUDES PARALLELIZATION WITH MPI
  find_package(MPI REQUIRED COMPONENTS Fortran C)
  set(MPI_Fortran_COMPILER "mpif90")
  set(MPI_C_COMPILER "mpicc")
endif()

# ENABLE EPA WATER QUALITY MOD
set(FVCOM_WATER_QUALITY OFF CACHE BOOL "ENABLE EPA WATER QUALITY MOD")

# ENABLE the Cartographic projection library
set(FVCOM_PROJ OFF CACHE BOOL "ENABLE the Cartographic projection library")

# ENABLE NUDGING BASED DATA ASSIMILATION FOR CURRENT/TEMP/SALINITY/SST
set(FVCOM_DATA_ASSIM OFF CACHE BOOL "ENABLE NUDGING BASED DATA ASSIMILATION FOR CURRENT/TEMP/SALINITY/SST")

# SELECT UPWIND LEAST SQUARE SCHEME
set(FVCOM_LIMITED "LIMITED_NO" CACHE STRING "SELECT UPWIND LEAST SQUARE SCHEME")
set_property(CACHE FVCOM_LIMITED PROPERTY STRINGS "LIMITED_NO;LIMITED_1;LIMITED_2")

# ENABLE Semi-Implicit time stepping method
set(FVCOM_SEMI_IMPLICIT OFF CACHE BOOL "ENABLE Semi-Implicit time stepping method")

# SELECT SOLID BOUNDARY TREATMENT
set(FVCOM_GCN "GCN" CACHE STRING "SELECT SOLID BOUNDARY TREATMENT")
set_property(CACHE FVCOM_GCN PROPERTY STRINGS "GCN;GCY1;GCY2")

# ENABLE GOTM TURBULENCE MODEL INSTEAD OF THE ORIGINAL FVCOM MELLOR-YAMADA 2.5 IMPLEMENTATION
set(FVCOM_GOTM OFF CACHE BOOL "ENABLE GOTM TURBULENCE MODEL")

# ENABLE EQUILIBRIUM TIDE
set(FVCOM_EQUI_TIDE OFF CACHE BOOL "ENABLE EQUILIBRIUM TIDE")

# ENABLE ATMOSPHERIC TIDE
set(FVCOM_ATMO_TIDE OFF CACHE BOOL "ENABLE ATMOSPHERIC TIDE")

# ENABLE RIVER DISTRIBUTION OPTION
set(FVCOM_RIVER_FLOAT OFF CACHE BOOL "ENABLE RIVER DISTRIBUTION OPTION")

# ENABLE THE TVD SCHEME
set(FVCOM_TVD OFF CACHE BOOL "ENABLE THE TVD SCHEME")

# Using A fully multidimensional positive definite advection transport algorithm with small implicit diffusion. 
set(FVCOM_MPDATA OFF CACHE BOOL "Using A fully multidimensional positive definite advection transport algorithm")

# Run Two-D Barotropic Mode Only
set(FVCOM_TWO_D_MODEL OFF CACHE BOOL "Run Two-D Barotropic Mode Only")

# Output 2-D Momentum Balance Checking
set(FVCOM_BALANCE_2D OFF CACHE BOOL "Output 2-D Momentum Balance Checking")

# OPEN BOUNDARY FORCING TYPE
set(FVCOM_MEAN_FLOW OFF CACHE BOOL "ENABLE OPEN BOUNDARY FORCING TYPE: MEAN_FLOW")

# OUTPUT TIDAL INFORMATION AT NTIDENODE and NTIDECELL
set(FVCOM_TIDE_OUTPUT OFF CACHE BOOL "OUTPUT TIDAL INFORMATION AT NTIDENODE and NTIDECELL")

# dye release
set(FVCOM_DYE_RELEASE OFF CACHE BOOL "ENBALE DYE RELEASE")

# ENABLE SUSPENDED SEDIMENT MODEL
set(FVCOM_SEDIMENT OFF CACHE BOOL "ENABLE SUSPENDED SEDIMENT MODEL")

# ENABLE KALMAN FILTERS
set(FVCOM_RRKF OFF CACHE BOOL "ENABLE KALMAN FILTERS")

# ENABLE One-D Mode with Biological Model
set(FVCOM_ONE_D_MODEL OFF CACHE BOOL "ENABLE One-D Mode with Biological Model")

# ENABLE GENERAL BIOLOGICAL MODEL
set(FVCOM_BioGen OFF CACHE BOOL "ENABLE GENERAL BIOLOGICAL MODEL")

# ENABLE Dynamic/Thermodynamic Ice 
set(FVCOM_ICE OFF CACHE BOOL "ENABLE Dynamic/Thermodynamic Ice ")

# SELECT THE NET HEAT FLUX CALCULATION
set(FVCOM_HEATFLUX "NONE" CACHE STRING "SELECT THE NET HEAT FLUX CALCULATION")
set_property(CACHE FVCOM_HEATFLUX PROPERTY STRINGS "NONE;HEATING_CALCULATED;HEATING_SOLAR")

# ENABLE AIR_PRESSURE FROM SURFACE FORCING
set(FVCOM_AIR_PRESSURE OFF CACHE BOOL "ENABLE AIR_PRESSURE FROM SURFACE FORCING")

# ENABLE NON-HYDROSTATIC MODEL
set(FVCOM_NH OFF CACHE BOOL "ENABLE NON-HYDROSTATIC MODEL")

# ENABLE PARTICLE TRACKING
set(FVCOM_LAG_PARTICLE OFF CACHE BOOL "ENABLE PARTICLE TRACKING")

# ENABLE WAVE-CURRENT INTERACTION
set(FVCOM_WAVE_CURRENT_INTERACTION OFF CACHE BOOL "ENABLE WAVE-CURRENT INTERACTION")

# ENABLE THIN-DAM MODEL
set(FVCOM_THIN_DAM OFF CACHE BOOL "ENABLE THIN-DAM MODEL")

# ENABLE PWP MIXED LAYER MODEL
set(FVCOM_PWP OFF CACHE BOOL "ENABLE PWP MIXED LAYER MODEL")

# ENABLE VERTICAL ADVECTION LIMITER
set(FVCOM_LIMITER_VER_ADV OFF CACHE BOOL "ENABLE VERTICAL ADVECTION LIMITER")

# ENABLE PETSC
set(FVCOM_OLD_PETSC OFF CACHE BOOL "ENABLE PETSC")

# ENABLE SPECIAL PARTITION
set(FVCOM_PARTITION_SPECIAL OFF CACHE BOOL "ENABLE SPECIAL PARTITION")

# ENABLE Vegetation Impact on FLows, Waves and Sediment
set(FVCOM_VEGETATION OFF CACHE BOOL "ENABLE VEGETATION Impact on FLows, Waves and Sediment")

# ENABLE PIO OUTPUT
set(FVCOM_PIO OFF CACHE BOOL "ENABLE PIO OUTPUT")

# GENERATING FVCOM LIBRARY FILE
set(FVCOM_COUPLED OFF CACHE BOOL "GENERATING FVCOM LIBRARY FILE")
